### ISSUE TITLE
看代码有疑问

### ISSUE THREAD

**Issue by ArvinCheng2019** [Joker-YF/JKFrame#1]
/// <summary>
        /// 启动一个协程序并且绑定某个对象
        /// </summary>
        public static Coroutine Start_Coroutine(object obj,IEnumerator routine)
        {
            Coroutine coroutine = null;
            if (instance.coroutineDic.TryGetValue(obj,out List<Coroutine> coroutineList))
            {
                coroutine = instance.StartCoroutine(routine);
                coroutineList.Add(coroutine);
            }
            else
            {
                coroutineList = poolModule.GetObject<List<Coroutine>>();
                if (coroutineList == null) coroutineList = new List<Coroutine>();
                coroutineList.Add(coroutine);
                instance.coroutineDic.Add(obj,coroutineList);
            }
            return coroutine;
        }

else 里是不是少调用了 一次     coroutine = instance.StartCoroutine(routine);

**Comment by Joker-YF** [comment]
是的，你说的没错，非常感谢反馈。已修复！




Joker
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Joker-YF/JKFrame"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月29日(星期天) 下午2:55
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Joker-YF/JKFrame] 看代码有疑问 (Issue #1)





   /// <summary&gt;     /// 启动一个协程序并且绑定某个对象     /// </summary&gt;     public static Coroutine Start_Coroutine(object obj,IEnumerator routine)     {         Coroutine coroutine = null;         if (instance.coroutineDic.TryGetValue(obj,out List<Coroutine&gt; coroutineList))         {             coroutine = instance.StartCoroutine(routine);             coroutineList.Add(coroutine);         }         else         {             coroutineList = poolModule.GetObject<List<Coroutine&gt;&gt;();             if (coroutineList == null) coroutineList = new List<Coroutine&gt;();             coroutineList.Add(coroutine);             instance.coroutineDic.Add(obj,coroutineList);         }         return coroutine;     }  
else 里是不是少调用了 一次     coroutine = instance.StartCoroutine(routine);
