### ISSUE TITLE
 UISystem.AddTips("CheckName")出现bug

### ISSUE THREAD

**Issue by laikaicool** [Joker-YF/JKFrame#12]
虽然消息对象池回收，但下次回收出现翻倍。如第一次回收1条Tips，下次取出1条后，回收变成了2条（回收节点始终应该一条）如图，导致对象池大量累积无效节点

![1696427757644](https://github.com/Joker-YF/JKFrame/assets/56617904/a73b13b4-bfbb-4d77-ace3-58ccf85bf1f4)

**Comment by UnParKs** [comment]
![UITips修复](https://github.com/Joker-YF/JKFrame/assets/58517089/98e7f260-506b-4852-9dc4-e0bedbc63887)
问题已修复，请等待同步，问题在于生成的UITips实例化之后要改名字要不然放回对象池的名字会多个Clone，取出来的时候和key不匹配对象池没办法重用，所以出现回收池堆积的情况。

![7U6G)VPJ% XL)})9IIUA~LS](https://github.com/Joker-YF/JKFrame/assets/58517089/983026d4-0f2b-4d8e-bc1f-145a58abb427)
