### ISSUE TITLE
使用最新团结引擎，odin插件就没法兼容了

### ISSUE THREAD

**Issue by zxhans** [Joker-YF/JKFrame#15]
请作者看看能否将odin去除或者升级一下兼容呢？毕竟未来，大家都会使用团结引擎进行开发微信小游戏的居多。。。谢谢

**Comment by Joker-YF** [comment]
有计划去除odin的，但可能需要一点时间
&nbsp;


Joker
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月4日(星期四) 上午9:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [Joker-YF/JKFrame] 使用最新团结引擎，odin插件就没法兼容了 (Issue #15)





 
请作者看看能否将odin去除或者升级一下兼容呢？毕竟未来，大家都会使用团结引擎进行开发微信小游戏的居多。。。谢谢

**Comment by Joker-YF** [comment]
实践了，没有兼容性问题啊~

**Comment by zxhans** [comment]
是的，重启ide就可以了，弹出这个安装就好了 
![image](https://github.com/Joker-YF/JKFrame/assets/52526052/b702952d-8dfc-49db-ae66-dec63cbaa6f9)
